
name: CI - Verification jobs

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
  compile:
    name: library compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - name: Install modules
        run: yarn
      - name: Run task
        run: yarn compile
